## Ex2) 
## Backpropagation Neural Network

In [1]:
import numpy as np
# X = (hours sleeping, hours studying), y = score on test
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
print(X)
print(y)
# scale units
X = X/np.amax(X, axis=0) # maximum of X array
y = y/100 # max test score is 100
print(X)
print(y)
class Neural_Network(object):
    def __init__(self):
 #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
 #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) 




    def forward(self, X):
 #forward propagation through our network
        self.z = np.dot(X, self.W1) 
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        o = self.sigmoid(self.z3) # final activation function
        return o 
    def sigmoid(self, s):
 # activation function 
        return 1/(1+np.exp(-s))
    def sigmoidPrime(self, s):
 #derivative of sigmoid
        return s * (1 - s)
    def backward(self, X, y, o):
 # backward propgate through the network
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) 
        self.z2_error = self.o_delta.dot(self.W2.T) 
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) 

        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) 
    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    print ("Input: \n" + str(X)) 
    print ("Actual Output: \n" + str(y)) 
    print ("Predicted Output: \n" + str(NN.forward(X))) 
    print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) 
    print ("\n")
    NN.train(X, y)

[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[92.]
 [86.]
 [89.]]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.62287047]
 [0.66667975]
 [0.61081683]]
Loss: 
0.06786730520600977


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.6404628 ]
 [0.68380428]
 [0.62854142]]
Loss: 
0.05918218823163712


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.65724618]
 [0.69963602]
 [0.64542247]]
Loss: 
0.05152478234236444


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.67319776]
 [0.71423823]
 [0.66144978]]
Loss: 
0.04479

Predicted Output: 
[[0.89130151]
 [0.88683702]
 [0.88282159]]
Loss: 
0.0005317861368639906


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89148602]
 [0.88695817]
 [0.88301379]]
Loss: 
0.0005295324440956991


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89166414]
 [0.88707432]
 [0.88319935]]
Loss: 
0.0005273961732760185


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89183614]
 [0.88718566]
 [0.88337854]]
Loss: 
0.0005253691084164935


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89200224]
 [0.88729239]
 [0.8835516 ]]
Loss: 
0.0005234436397386482


Input: 
[[0.66666667 1.        ]
 [

 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89583444]
 [0.88922634]
 [0.88754672]]
Loss: 
0.0004813907404645947


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89587312]
 [0.88923261]
 [0.887587  ]]
Loss: 
0.0004808247668274491


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89591071]
 [0.88923801]
 [0.88762614]]
Loss: 
0.00048026341623683475


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89594725]
 [0.88924258]
 [0.88766417]]
Loss: 
0.00047970643051772487


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89598278]
 [0.88924635]
 [0.88770114

Loss: 
0.0004617907971504337


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89678593]
 [0.88903224]
 [0.88853295]]
Loss: 
0.00046130532079830655


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8968005 ]
 [0.88901959]
 [0.88854787]]
Loss: 
0.000460820763126523


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89681476]
 [0.88900672]
 [0.88856249]]
Loss: 
0.00046033710271492387


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89682874]
 [0.88899362]
 [0.88857679]]
Loss: 
0.00045985431946692876


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Outp

 [0.88928356]]
Loss: 
0.00041948940277443695


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89755419]
 [0.88743837]
 [0.88928889]]
Loss: 
0.0004190614134118823


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89755996]
 [0.88741985]
 [0.88929421]]
Loss: 
0.00041863395814796224


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89756572]
 [0.88740134]
 [0.88929951]]
Loss: 
0.0004182070363018599


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89757147]
 [0.88738284]
 [0.88930478]]
Loss: 
0.00041778064719573795


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.666666

0.0003995369862535093


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89782178]
 [0.88655761]
 [0.8895291 ]]
Loss: 
0.0003991338968474195


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89782723]
 [0.8865395 ]
 [0.88953388]]
Loss: 
0.0003987313106219665


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89783269]
 [0.88652141]
 [0.88953864]]
Loss: 
0.0003983292269540582


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89783814]
 [0.88650332]
 [0.88954341]]
Loss: 
0.00039792764522118693


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89830344]
 [0.88499725]
 [0.88993518]]
Loss: 
0.0003652024205441446


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89830884]
 [0.88498032]
 [0.88993957]]
Loss: 
0.000364842188367837


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89831424]
 [0.88496341]
 [0.88994395]]
Loss: 
0.0003644824055688897


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89831964]
 [0.88494651]
 [0.88994833]]
Loss: 
0.0003641230715758495


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Pred

Predicted Output: 
[[0.89871899]
 [0.8837332 ]
 [0.89026313]]
Loss: 
0.0003387384178593167


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89872438]
 [0.8837173 ]
 [0.89026726]]
Loss: 
0.0003384111587997954


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89872977]
 [0.88370141]
 [0.89027139]]
Loss: 
0.0003380843068386716


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89873516]
 [0.88368553]
 [0.89027552]]
Loss: 
0.00033775786144968394


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89874055]
 [0.88366967]
 [0.89027964]]
Loss: 
0.0003374318221071513


Input: 
[[0.66666667 1.        ]
 

 [0.89]]
Predicted Output: 
[[0.89909012]
 [0.88266586]
 [0.89054065]]
Loss: 
0.0003170855208189812


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89909548]
 [0.88265083]
 [0.89054457]]
Loss: 
0.0003167851470773907


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89910084]
 [0.88263581]
 [0.89054847]]
Loss: 
0.0003164851454675357


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89910621]
 [0.88262081]
 [0.89055238]]
Loss: 
0.000316185515502477


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89911157]
 [0.88260581]
 [0.89055628]]
Loss: 
0.0003158862566958377


Input: 
[[0.66666667 1.    

Loss: 
0.00029392033005556185


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89952778]
 [0.88147347]
 [0.89085092]]
Loss: 
0.0002936485684109177


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89953309]
 [0.88145942]
 [0.89085457]]
Loss: 
0.00029337714123677325


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89953839]
 [0.88144538]
 [0.89085822]]
Loss: 
0.0002931060480902989


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8995437 ]
 [0.88143135]
 [0.89086187]]
Loss: 
0.00029283528852920197


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Out

Loss: 
0.00028330642423000387


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89973939]
 [0.88092036]
 [0.89099472]]
Loss: 
0.000283047701192383


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89974466]
 [0.88090676]
 [0.89099825]]
Loss: 
0.0002827892953210292


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89974993]
 [0.88089318]
 [0.89100178]]
Loss: 
0.00028253120619396927


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8997552 ]
 [0.8808796 ]
 [0.89100531]]
Loss: 
0.0002822734333897486


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Outpu

 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89999133]
 [0.88028025]
 [0.89116088]]
Loss: 
0.0002709943165002501


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89999655]
 [0.88026718]
 [0.89116427]]
Loss: 
0.0002707506477416945


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90000178]
 [0.88025412]
 [0.89116765]]
Loss: 
0.00027050727606884895


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.900007  ]
 [0.88024108]
 [0.89117103]]
Loss: 
0.00027026420108440253


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90001222]
 [0.88022804]
 [0.89117441

Predicted Output: 
[[0.90027184]
 [0.87958979]
 [0.89133961]]
Loss: 
0.00025825163290442546


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.900277  ]
 [0.87957729]
 [0.89134284]]
Loss: 
0.00025802345031833185


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90028216]
 [0.8795648 ]
 [0.89134607]]
Loss: 
0.0002577955440581213


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90028732]
 [0.87955233]
 [0.89134929]]
Loss: 
0.0002575679137524968


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90029248]
 [0.87953986]
 [0.89135251]]
Loss: 
0.0002573405590306238


Input: 
[[0.66666667 1.        ]


 [0.89159785]]
Loss: 
0.00024021955060746095


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90070126]
 [0.87857512]
 [0.89160085]]
Loss: 
0.00024001308190831194


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90070631]
 [0.87856346]
 [0.89160383]]
Loss: 
0.0002398068602761837


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90071137]
 [0.87855181]
 [0.89160682]]
Loss: 
0.00023960088537731378


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90071643]
 [0.87854017]
 [0.8916098 ]]
Loss: 
0.00023939515687834492


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666

Predicted Output: 
[[0.90101725]
 [0.87785899]
 [0.89178375]]
Loss: 
0.0002274900067870795


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90102223]
 [0.87784792]
 [0.89178656]]
Loss: 
0.00022729869527989376


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9010272 ]
 [0.87783686]
 [0.89178938]]
Loss: 
0.00022710761033443926


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90103217]
 [0.87782581]
 [0.89179219]]
Loss: 
0.00022691675164382386


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90103713]
 [0.87781477]
 [0.89179499]]
Loss: 
0.00022672611890157195


Input: 
[[0.66666667 1.        